### ISSUE TITLE
`ValueError: numpy.ndarray size changed`

### ISSUE THREAD

**Issue by galenseilis** [scikit-tda/ripser.py#141] opened 2022-03-17 04:33 UTC
On Ubuntu (current LTS) the command `pip install scikit-tda` appeared to work without error. However running the import for ripser gives a value error.

```python
>>> import ripser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/galen/.local/lib/python3.8/site-packages/ripser/__init__.py", line 1, in <module>
    from .ripser import *
  File "/home/galen/.local/lib/python3.8/site-packages/ripser/ripser.py", line 34, in <module>
    from pyRipser import doRipsFiltrationDM as DRFDM
  File "ripser/pyRipser.pyx", line 1, in init pyRipser
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by ZWAdams** [comment] 2022-06-22 23:48
I got the same error. Any updates on this?

**Comment by ctralie** [comment] 2022-06-23 00:46
Try to run

pip install --upgrade numpy

**Comment by ZWAdams** [comment] 2022-06-23 01:49
Thanks for responding! I tried that, still not working. I'm running on an M1 chip, could that be part of the issue?

**Comment by ctralie** [comment] 2022-08-16 12:32
What I'd do is create an entirely new environment in conda and make ripser.py the first thing you install there

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by ctralie** [comment] 2022-10-11 09:16
My gut says no, but I'm honestly not sure.  I will look into this as soon
as I can.  Sorry for the trouble!

**Comment by catanzaromj** [comment] 2024-07-06 16:07
It's unclear if this is still a bug or not. I can't reproduce it. Regardless, we'll compile ripser with numpy 2.0.0, so that should provide another fix for this problem.

**Comment by catanzaromj** [comment] 2024-07-20 13:37
Closing as I can't reproduce. Re-open if it is still a problem.

**Closed by catanzaromj** 2024-07-20 13:37 UTC
Labels: bug, dependencies
