### ISSUE TITLE
Threshold gives unexpected result.

### ISSUE THREAD

**Issue by mbr085** [scikit-tda/ripser.py#51] opened 2018-10-31 11:46 UTC
Please see https://github.com/Ripser/ripser/issues/20

**Comment by mbr085** [comment] 2018-11-04 22:06
In short the problem is that the thresh option produces results that are different from the results of the classic command line ripser.

```python
from ripser import ripser, plot_dgms
import itertools
import numpy as np

n=3
segment = [np.linspace(0,1,5)]
endpoints = [np.linspace(0,1,2)]
face = segment * (n - 1) + endpoints
vertices = []
for k in range(n):
    vertices.extend(itertools.product(*(face[k:] + face[:k])))
    coords = np.array(corners)

rips = ripser(coords, maxdim=2, thresh=.8)
plot_dgms(rips['dgms'])
```

exporting to a file
```python
np.savetxt('box.txt', X=coords)
```
and running ripser gives a different result.

**Comment by ctralie** [comment] 2018-11-05 03:29
Sorry for the trouble, and thank you for the detailed report!  I will have a look tomorrow

**Comment by ctralie** [comment] 2018-11-06 13:10
Hello,
Here's where I am so far, comparing this to GUDHI:

![ripserpy_vs_gudhi](https://user-images.githubusercontent.com/1270246/48066311-3cbd0080-e19b-11e8-95ca-eb9aaf6e1027.png)


Code below.  0D and 1D persistent homology looks the same, but GUDHI is missing the 2D dot.  I should note that in our ripser.py, the 2D dot is born when all of the 1D dots die.  This makes sense from the point cloud you setup, so that seems correct to me.  This is also the case from ripser in the command line, but the result is different, as you noted.

I'll dig into this more deeply in a few hours when I get back from some meetings.  For now, here's the code I wrote:


~~~~python
from ripser import ripser, plot_dgms
import gudhi
import itertools
import numpy as np
import matplotlib.pyplot as plt

def convertGUDHIPD(pers):
    """
    Convert GUDHI persistence diagrams into a list of arrays
    """
    Is = {}
    for i in range(len(pers)):
        (dim, (b, d)) = pers[i]
        if not dim in Is:
            Is[dim] = []
        Is[dim].append([b, d])
    Is = [np.array(Is[dim]) for dim in Is]
    return Is

n=3
segment = [np.linspace(0,1,5)]
endpoints = [np.linspace(0,1,2)]
face = segment * (n - 1) + endpoints
vertices = []
for k in range(n):
    vertices.extend(itertools.product(*(face[k:] + face[:k])))
coords = np.array(vertices)
np.savetxt('box.txt', X=coords)

rips = ripser(coords, maxdim=2)
dgmsrips = rips['dgms']


rips_complex = gudhi.RipsComplex(points=coords,max_edge_length=1e9)
simplex_tree = rips_complex.create_simplex_tree(max_dimension=2)
dgmsgudhi = simplex_tree.persistence(homology_coeff_field=2, min_persistence=0)
dgmsgudhi = convertGUDHIPD(dgmsgudhi)

plt.figure(figsize=(10, 5))
plt.subplot(121)
plot_dgms(dgmsrips, xy_range=[-0.2, 1.5, 0, 1.5])
plt.title("Ripser")
plt.subplot(122)
plot_dgms(dgmsgudhi, xy_range=[-0.2, 1.5, 0, 1.5])
plt.show()
~~~~

**Comment by mbr085** [comment] 2018-11-06 13:53
Using GUDHI you need to add simplices dimension 3 in order to compute homology in dimension 2.
I have taken the liberty to modify your script so that it contains both the GUDHI and the ripser results. You will notice that they agree.
```python
%matplotlib inline
from ripser import ripser, plot_dgms
import gudhi
import itertools
import numpy as np
import matplotlib.pyplot as plt
def convertGUDHIPD(pers):
    """
    Convert GUDHI persistence diagrams into a list of arrays
    """
    Is = {}
    for i in range(len(pers))[::-1]:
        (dim, (b, d)) = pers[i]
        if not dim in Is:
            Is[dim] = []
        Is[dim].append([b, d])
    Is = [np.array(Is[dim]) for dim in Is]
    return Is

n=3
segment = [np.linspace(0,1,5)]
endpoints = [np.linspace(0,1,2)]
face = segment * (n - 1) + endpoints
vertices = []
for k in range(n):
    vertices.extend(itertools.product(*(face[k:] + face[:k])))
coords = np.array(vertices)
np.savetxt('box.txt', X=coords)

rips = ripser(coords, maxdim=2)
dgmsrips = rips['dgms']


rips_complex = gudhi.RipsComplex(points=coords) #,max_edge_length=1e9)
simplex_tree = rips_complex.create_simplex_tree(max_dimension=3)
dgmsgudhi2 = simplex_tree.persistence(homology_coeff_field=2)
dgmsgudhi = convertGUDHIPD(dgmsgudhi2)

plt.figure(figsize=(10, 5))
plt.subplot(121)
plot_dgms(dgmsrips, xy_range=[-0.2, 1.5, 0, 1.5])
plt.title("Ripser")
plt.subplot(122)
plot_dgms(dgmsgudhi, xy_range=[-0.2, 1.5, 0, 1.5])
plt.title('GUDHI')
plt.show()
```
![image](https://user-images.githubusercontent.com/7124203/48068656-b2dd5980-e1d3-11e8-9c84-ae79360ffc03.png)

This is in contrast to the situation where a threshold is introduced:
```python
%matplotlib inline
from ripser import ripser, plot_dgms
import gudhi
import itertools
import numpy as np
import matplotlib.pyplot as plt

def convertGUDHIPD(pers):
    """
    Convert GUDHI persistence diagrams into a list of arrays
    """
    Is = {}
    for i in range(len(pers))[::-1]:
        (dim, (b, d)) = pers[i]
        if not dim in Is:
            Is[dim] = []
        Is[dim].append([b, d])
    Is = [np.array(Is[dim]) for dim in Is]
    return Is

n=3
segment = [np.linspace(0,1,5)]
endpoints = [np.linspace(0,1,2)]
face = segment * (n - 1) + endpoints
vertices = []
for k in range(n):
    vertices.extend(itertools.product(*(face[k:] + face[:k])))
coords = np.array(vertices)
np.savetxt('box.txt', X=coords)

rips = ripser(coords, maxdim=2, thresh=1.4)
dgmsrips = rips['dgms']


rips_complex = gudhi.RipsComplex(points=coords) #,max_edge_length=1e9)
simplex_tree = rips_complex.create_simplex_tree(max_dimension=3)
dgmsgudhi2 = simplex_tree.persistence(homology_coeff_field=2)
dgmsgudhi = convertGUDHIPD(dgmsgudhi2)

plt.figure(figsize=(10, 5))
plt.subplot(121)
plot_dgms(dgmsrips, xy_range=[-0.2, 1.5, 0, 1.5])
plt.title("Ripser")
plt.subplot(122)
plot_dgms(dgmsgudhi, xy_range=[-0.2, 1.5, 0, 1.5])
plt.title('GUDHI')
plt.show()
```
![image](https://user-images.githubusercontent.com/7124203/48068619-917c6d80-e1d3-11e8-8bda-940cc47556a2.png)

**Comment by ctralie** [comment] 2018-11-06 16:06
Interesting, thanks for the update!  I will have a look.

By the way, if you're looking to do 2D homology efficiently in low dimensions, you might check out alpha filtrations:
http://gudhi.gforge.inria.fr/doc/latest/group__alpha__complex.html

I still definitely want to fix this bug though, so thanks for pointing it out!

**Comment by ctralie** [comment] 2018-11-06 17:03
@ubauer I could use your help on this.  Do you have any idea why the command line version gives something completely different? (Output below)
It doesn't make any sense, because it only has one connected component, but it has a bunch of 1D classes that are born at 0?

I have also noticed that in our wrapper, it seems to be a problem in the sparse matrix class.  When I use a dense matrix, it seems to work correctly with all thresholds.  Though in the command line version, the answer is the same regardless.  Any ideas?

value range: [0,1]
sparse distance matrix with 30 points and 310/449 entries
persistence intervals in dim 0:
 [0, )
persistence intervals in dim 1:
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
 [0,0.25)
persistence intervals in dim 2:
 [0.25,0.5)
 [0.25,0.5)
 [0.25,0.75)
 [0.25,0.5)
 [0.25,0.5)
 [0.25,0.5)
 [0.25,0.5)
 [0.25,0.5)
 [0.25,0.5)
 [0.25,0.5)
 [0.25,0.5)
 [0,0.5)

**Comment by ubauer** [comment] 2018-11-06 19:48
Hi Chris,

It seems that you didn’t specify the input format as `--point-cloud`. With that, you should get the expected results.

I don’t know what’s happening in the wrapper, but if i remember correctly you're not using Ripser to compute the distance matrix for a point cloud, but some extra Python code. Maybe the problem is related to that?

**Comment by ctralie** [comment] 2018-11-06 20:09
Hi Uli,
Thanks for the quick response.  Ah okay that completely explains it with what's happening in the console.

Yeah I also thought that about the custom code, but the same bug occurs with a sparse distance matrix.  Something is going wrong with how I'm interfacing with the sparse distance matrix class in ripser....

**Comment by mbr085** [comment] 2018-11-13 08:58
I tried to test it but saw no difference. Is there an easy way to confirm that I am running the updated version of the code?

**Comment by ctralie** [comment] 2018-11-13 12:17
Try pip uninstall ripser first.  I had a similar issue before.

**Comment by sauln** [comment] 2018-11-13 20:35
If you reinstall the source from the branch now, you should be able to confirm you're running the updated code by checking the version:
```
python -c "import ripser; print(ripser.__version__)"
>>> 0.3.0.dev0
```

The output should be `0.3.0.dev0` rather than `0.3.0` as is on the master branch.

**Comment by sauln** [comment] 2018-11-14 00:43
A fix has been issued to master. We'll roll out a new version to Pypi asap. If it persists for you @mbr085 , please let us know and reopen the issue.

Thank you.

**Closed by sauln** 2018-11-14 00:43 UTC

**Comment by mbr085** [comment] 2018-11-14 07:14
I confirm that the issue is resolved.

**Comment by ctralie** [comment] 2018-11-14 12:32
Great! Thank you so much for the detailed report! This was a subtle one
because few people use H2 and when I use it I don't use thresholds

**Comment by ubauer** [comment] 2018-11-14 12:55
Thanks to everyone! Chris, you're right, the sorting is essential, and the behavior we saw is expected.
